language: python
python:
  - "3.6"

# command to install dependencies
install: "pip install -r requirements.txt"

env:
  - DATABASE_URI=postgres://postgres:@localhost:5432/test

# commands to run tests
before_script:
  - psql -c "create database testdb;" -U postgres

script:
  - nosetests

after_success:
  - codecov

services:
  - postgresql
