sudo: required

language: python
python:
  - '3.7'

addons:
  chrome: stable

services:
  - docker

before_install:
  - docker pull postgres:alpine
  - docker run -d --name postgres -p 5432:5432 -e POSTGRES_PASSWORD=postgres postgres:alpine
  - docker ps -a

env:
  - DATABASE_URI="postgres://postgres:postgres@localhost:5432/postgres"
# command to install dependencies

install:
  - sudo apt-get install -y chromium-chromedriver python3-selenium
  - pip install -r requirements.txt

before_script:
  - chromedriver --version
  - gunicorn --log-level=info --bind=127.0.0.1:5000 service:app &  #  start a Web server in the background
  - sleep 5 # give Web server some time to bind to sockets, etc
  - curl -I http://localhost:5000/  # make sure the service is up

script:
  - behave
  - nosetests

after_success:
  - codecov